INSERT INTO airline.airport (airport_designator, airport_name) VALUES
('EGLL', 'London Heathrow Airport'),
('LFPG', 'Charles de Gaulle Airport'),
('EDDF', 'Frankfurt Airport'),
('EHAM', 'Amsterdam Schiphol Airport'),
('LTFM', 'Istanbul Airport'),
('LEMD', 'Adolfo Suárez Madrid–Barajas Airport'),
('EDDM', 'Munich Airport'),
('LPPT', 'Lisbon Humberto Delgado Airport'),
('LSZH', 'Zurich Airport'),
('LOWW', 'Vienna International Airport'),
('LEMD', 'Leonardo da Vinci International Airport'),
('EBBR', 'Brussels Airport'),
('EKCH', 'Copenhagen Airport'),
('ESSA', 'Stockholm Arlanda Airport'),
('EFHK', 'Helsinki-Vantaa Airport'),
('ENGM', 'Oslo Gardermoen Airport'),
('EPWA', 'Warsaw Chopin Airport'),
('EPGD', 'Gdańsk Lech Wałęsa Airport'),
('EPKK', 'Kraków John Paul II International Airport'),
('EPWR', 'Wrocław Copernicus Airport'),
('EPKT', 'Katowice Airport'),
('LEBL', 'Barcelona El Prat Airport'),
('EIDW', 'Dublin Airport'),
('LPPR', 'Porto Airport'),
('LIRF', 'Rome Fiumicino Airport'),
('LIMC', 'Milan Malpensa Airport'),
('SBBE', 'Belém–Val de Cans–Júlio Cezar Airport'),
('EETN', 'Tallinn Lennart Meri Airport'),
('UKBB', 'Boryspil International Airport'),
('LFPO', 'Paris Orly Airport'),
('LBSF', 'Sofia Airport'),
('LJLJ', 'Ljubljana Jože Pučnik Airport'),
('LHBP', 'Budapest Ferenc Liszt International Airport'),
('LROP', 'Henri Coandă International Airport'),
('LWSK', 'Skopje Alexander the Great Airport'),
('UGTB', 'Tbilisi International Airport'),
('LCLK', 'Larnaca International Airport'),
('UUEE', 'Sheremetyevo International Airport'),
('UUDD', 'Domodedovo International Airport'),
('ULLI', 'Pulkovo Airport'),
('EVRA', 'Riga International Airport'),
('LDZA', 'Zagreb Franjo Tuđman Airport'),
('LIPZ', 'Venice Marco Polo Airport'),
('EGKK', 'London Gatwick Airport'),
('EGMC', 'London Southend Airport'),
('EGLC', 'London City Airport'),
('EIN', 'Eindhoven Airport'),
('EGSS', 'Stansted Airport'),
('EGMC', 'London Luton Airport'),
('BGO', 'Bergen Airport'),
('ENVA', 'Trondheim Airport'),
('LMML', 'Malta International Airport'),
('LKPR', 'Václav Havel Airport Prague'),
('LDPL', 'Pula Airport'),
('LEVC', 'Valencia Airport'),
('LEPA', 'Palma de Mallorca Airport'),
('LEIB', 'Ibiza Airport'),
('LEMG', 'Málaga-Costa del Sol Airport'),
('LLBG', 'Ben Gurion International Airport'),
('EVAA', 'Riga International Airport'),
('LSGG', 'Geneva Airport'),
('ELLX', 'Luxembourg Airport'),
('LIRA', 'Fiumicino Airport'),
('LFTH', 'Toulon-Hyères Airport'),
('LZIB', 'Bratislava Airport'),
('EDDB', 'Berlin Brandenburg Airport'),
('LTFM', 'Istanbul New Airport'),
('EGKK', 'London Gatwick Airport'),
('EGMC', 'London Southend Airport'),
('EGLL', 'London Heathrow Airport'),
('EDDB', 'Berlin Brandenburg Airport'),
('EGMC', 'London City Airport'),
('EIN', 'Eindhoven Airport'),
('EKCH', 'Copenhagen Airport'),
('EPKK', 'Kraków John Paul II International Airport'),
('LSZH', 'Zurich Airport'),
('LIRF', 'Rome Fiumicino Airport');

