INSERT INTO linia.lotnisko (lotnisko_kod, lotnisko_nazwa) VALUES
('EGLL', 'London Heathrow Airport'),
('LFPG', 'Charles de Gaulle Airport'),
('EDDF', 'Frankfurt Airport'),
('EHAM', 'Amsterdam Schiphol Airport'),
('LTFM', 'Istanbul Airport'),
('LEMD', 'Adolfo Suárez Madrid–Barajas Airport'),
('EDDM', 'Munich Airport'),
('LPPT', 'Lisbon Humberto Delgado Airport'),
('LSZH', 'Zurich Airport'),
('LOWW', 'Vienna International Airport'),
('LEMD', 'Leonardo da Vinci International Airport'),
('EBBR', 'Brussels Airport'),
('EKCH', 'Copenhagen Airport'),
('ESSA', 'Stockholm Arlanda Airport'),
('EFHK', 'Helsinki-Vantaa Airport'),
('ENGM', 'Oslo Gardermoen Airport'),
('EPWA', 'Warsaw Chopin Airport'),
('EPGD', 'Gdańsk Lech Wałęsa Airport'),
('EPKK', 'Kraków John Paul II International Airport'),
('EPWR', 'Wrocław Copernicus Airport'),
('EPKT', 'Katowice Airport'),
('LEBL', 'Barcelona El Prat Airport');

